---
- hosts: dev_servers
  user: root
  sudo: true
  roles:
  - java
  - memcached
  - htop
  - nginx
  - mysql

- hosts: www_servers
  user: root
  sudo: true
  roles:
  - htop
  - apache
  - iptables
  - vsftpd
