- name: Add EPEL Repo
  yum:
    name: "epel-release"
    state: present
  tags:
    - nginx


- name: Install NGinx
  yum:
    name: "nginx"
    state: present
  tags:
    - nginx

- name: Copy nginx.conf to the server
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - reload nginx
  tags:
    - nginx
