- name: Install Apache WEB Server
  yum:
    name: "httpd"
    state: present
  tags:
    - Apache

- name: Start Apache WEB Server
  service:
    name: httpd
    state: restarted
  tags:
    - Apache

- name: Enable Apache WEB Server
  service:
    name: httpd
    enabled: yes
