---
# - name: Install Python PIP
#   easy_install:
#        name: pip
#        state: latest

# - name: Install Python MySQL Libraries
#   pip:
#     name: MySQL-python
#     state: latest

 - name: Install the MySQL packages
   yum:
     name: "{{ item }}" 
     state: latest
     update_cache: yes
   with_items:
     - mariadb-server
     - mariadb

 - name: Update MySQL root password for all root accounts
   mysql_user: 
     name: root 
     password: "{{ mysql_root_pass }}" 
     state: present
   with_items:
     - "{{ ansible_hostname }}"
     - 127.0.0.1
     - ::1
     - localhost

 - name: Copy the root credentials as .my.cnf file
   template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

 - name: Ensure Anonymous user(s) are not in the database
   mysql_user: 
     name: '' 
     host: "{{ item }}" 
     state: absent
   with_items:
     - localhost
     - "{{ ansible_hostname }}"

 - name: Remove the test database
   mysql_db: 
     name: test 
     state: absent
   notify:
     - Restart MySQL
